<?php
/**
 * Define what our block is going to look like.
 * Implements hook_block_view().
 */


function myblockmodule_menu() {
    $items = array();
    
    $items['magic'] = array(
        'title' => 'A little 2 magic',
        'page callback' => 'menu_magic_basic',
        'access arguments' => array('access content'),
    );
    
    return $items;
  }
  
  function menu_magic_basic() {
    $content = array();
    
    return $content;
  }
  
  function myblockmodule_views_pre_view(&$view) {

      if ($view->name == 'testview') {

          //$view->init_display('default');
          //$view->display_handler->display->display_options['filters']['field_raum']['default'] = 'Implementierungsraum';
          //$view->is_cacheable = FALSE;
          //$view->execute();
          //print $view->render();

          //  $view->init_display();

          //$filter = $view->get_item($view->current_display, 'filter', 'field_raum');
          //$filter['filter']['field_raum'] = 'Implementierungsraum';
          //$view->set_item($view->current_display, 'filter', 'field_raum', $filter);

          //$view->execute();
          //$result = $view->result;
      }

      //$view_filters = $view->display_handler->get_option('filters');


      //$view_filters['field_raum']['value'] = 'Implementierungsraum';
      //$view->display_handler->override_option('filters', $view_filters);


        //$filters = $view->display_handler->get_option('filters');


        //$view->display['page']->handler->handlers['filter']['field_raum']->value['value'] = 'Raum';




        //$view->display['default']->handler->options['title']='Testtitel';
        //$view_filters['field_raum']['value'] = 'Implementierungsraum';
        //$view->display_handler->override_option('filters', $view_filters);
        //$view->display['default']->handler->options['title'] = "this is the new title";
        //$view_filters = $view->display_handler->get_option('filters');
        //$view_filters['field_phase']['value'] = 'Implementierungsraum';
        //$overrides = array();
        //$overrides['filters'] = $view_filters;
        //foreach ($overrides as $option => $definition) {
        //    $view->display_handler->override_option($option, $definition);
        //}
        //$view->execute();
       //dpm($view);
       //print current_path();
        //print $view->get_title();

        //return $view;
    //}
}

function fix_missing_relationships()
{
    if (isset($this->relationships_fixed)) {
        return;
    }
}

