<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 02.11.16
 * Time: 15:03
 */

function mail_function_menu()
{
    $items['mail'] = array(
        'type' => MENU_CALLBACK,
        'access arguments' => array('access content'),
        'page callback' => 'drupal_get_form',
        'access callback' => 'user_is_logged_in',
        'page arguments' => array('mail_function_form'),
    );

    return $items;
}


//Diese Funktion erstellt ein Formular, in das alle Bestandteile einer Mail eingegeben werden können.
function mail_function_form($form, &$form_submit)
{

    //Mailadresse des Nutzers werden ermittelt
    global $user;
    $user = user_load($user->uid);
    $mail = $user->mail;

    //Die Adresse des Absenders entspricht der Mail-Adresse, mit der sich der Nutzer im Informationssystem
    //angemeldet hat
    $sender = "<b>Absender</b><br>$mail<br> <br>";

    $form['mail'] = array(
        '#title' => "Mail versenden",
        '#type' => 'fieldset',
        '#description' => "Es kann eine Mail an einen beliebigen Empfänger versendet werden.
            Die Adresse des Absenders ist standardmäßig die registrierte Mail-Adresse des Benutzers."
    );

    $form['mail']['from'] = array(
        '#type' => 'markup',
        '#prefix' => $sender,
    );

    $form['mail']['to'] = array(
        '#type' => 'textfield',
        '#require' => TRUE,
        '#title' => t('Empfänger:'),
        '#default_value' => ''
    );

    $form['mail']['cc'] = array(
        '#type' => 'textfield',
        '#require' => TRUE,
        '#title' => t('cc:'),
        '#default_value' => ''
    );

    $form['mail']['subject'] = array(
        '#type' => 'textfield',
        '#require' => TRUE,
        '#title' => t('Betreff:'),
        '#default_value' => ''
    );

    $form['mail']['body'] = array(
        '#title' => t('Inhalt:'),
        '#resizable' => FALSE,
        '#type' => 'textarea',
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Mail versenden',
        '#submit' => array('mail_function_send_mail')
    );

    return $form;
}

/*
 * Diese Funktion liest die vom Benutzer eingegebenen Felder aus und gibt die Informationen weiter, sodass ein
 * Mail-Objekt gebaut werden kann, welches im Anschluss abgeschickt wird.
 */
function mail_function_send_mail($form, &$form_state)
{


    //Mail-Adresse des Nutzers ermitteln
    global $user;
    $user = user_load($user->uid);
    $mail = $user->mail;

    //Attribute der Mail aus den Formular-Feldern laden
    $from = $mail;
    $to = $form_state['values']['to'];
    $cc = $form_state['values']['cc'];
    $subject = $form_state['values']['subject'];
    $body = $form_state['values']['body'];

    //Mail wird gesendet
    mail_function_send_personal_mail($from, $to, $cc, $subject, $body);
}

/*
 * Diese Funktion empfängt die vom Benutzer eingegebenen Daten und baut daraus ein Mail-Objekt, welches im
 * Anschluss abgeschickt wird.
 */
function mail_function_send_personal_mail($from, $to, $cc, $subject, $body)
{

    $fake_module = 'foo';
    $fake_key = 'bar';

    $message = array(
        'id' => $fake_module . '_' . $fake_key,
        'from' => $from,
        'to' => $to,
        'subject' => $subject,
        'body' => $body,
        'headers' => array(
            'Return-Path' => $from,
            'MIME-Version' => '1.0',
            'Content-Transfer-Encoding' => '8Bit',
            'Content-Type' => 'text/plain; charset=UTF-8;',
        ),
    );

    //Mail-Element wird validiert
    $system = drupal_mail_system($fake_module, $fake_key);

    //Falls Mail erfolgreich versendet wurde
    if ($system->mail($message)) {
        drupal_set_message("Email wurde gesendet!");
    } else {
        drupal_set_message("Email wurde nicht gesendet!", "error");
    }
}

//Vorgefertigte Funktion von Drupal, welche die Mail abschickt
function mail_function_mail($key, &$message, $params)
{
    switch ($key) {
        case 'newsletter':
            $headers = array(
                'MIME-Version' => '1.0',
                'Content-Type' => 'text/html; charset=UTF-8;',
                'Content-Transfer-Encoding' => '8Bit',
                'X-Mailer' => 'Drupal'
            );

            foreach ($headers as $key => $value) {
                $message['headers'][$key] = $value;
            }
            $message['subject'] = $params['subject'];
            $message['body'] = array(0 => t($params['body']));
            break;
    }
}