<?php
/**
 * Created by PhpStorm.
 * User: kortum
 * Date: 03.11.2015
 * Time: 19:20
 */

/**
 * Implements block_info
 */
function project_management_block_info() {
    $blocks['project_management'] = array(
        // The name that will appear in the block list.
        'info' => t('project management'),
        // Default setting.
        'cache' => DRUPAL_CACHE_PER_ROLE,
    );
    return $blocks;
}

/**
 * Custom content function.
 *
 * Gets all Documents from the group of the current user.
 *
 * @return
 *   A result set of documents
 */
function project_management_getDocuments(){

    //Current User
    global $user;

    //Use Database API to retrieve group documents.

    $result = db_query("SELECT node.nid, node.title, users.name, deadline.field_deadline_value FROM {node} AS node INNER JOIN {field_data_field_gruppenmitglied} as mitglied ON node.nid = mitglied.entity_id INNER JOIN {field_data_field_deadline} AS deadline ON node.nid = deadline.entity_id INNER JOIN {users} as users ON mitglied.field_gruppenmitglied_target_id = users.uid WHERE users.uid IN(SELECT users.uid FROM {users} AS users INNER JOIN {users_roles} AS zwischentabelle ON users.uid = zwischentabelle.uid INNER JOIN {role} AS role ON zwischentabelle.rid = role.rid WHERE role.rid = (SELECT role.rid FROM {users} AS users INNER JOIN {users_roles} AS zwischentabelle ON users.uid = zwischentabelle.uid INNER JOIN {role} AS role ON zwischentabelle.rid = role.rid WHERE users.uid = :user_id))ORDER BY deadline.field_deadline_value ASC;", array(
        ':user_id' => $user->uid,
    ));


        return $result;
}

/**
 * Implements hook_block_view().
 *
 * Prepares the contents of the block.
 */
function project_management_block_view($delta = '') {
    switch ($delta) {
        case 'project_management':

            // get group documents
            $result = project_management_getDocuments();


            $tempString = "<table><th>zugehöriger Benutzer (Wer?)</th> <th> Aufgabe (Was?)</th> <th>Deadline (Wann?)</th>";
                //save each method name in an array to read it out in the next step
                foreach ($result as $method) {


                    $tmp = $method->field_deadline_value;
                    $array = explode ( "T" , $tmp );
                    $tempString = $tempString . '<tr><td>'.$method->name.'</td><td>'.l($method->title, 'node/' . $method->nid).'</td><td>'. $array[0] . " " . $array[1] .' Uhr</td></tr>';
            }

            $tempString = $tempString . '</table>';

            $items[] = array(
                'data' => $tempString);


            if(user_is_logged_in()) {
                // No content was found.
                if (empty($items)) {
                    $block['content'] = t('Bisher wurden keine Aufgaben verteilt!');
                } else {
                    // Pass data through theme function.
                    $block['content'] = t($tempString);
                }
            } else {
                $block['content'] = t('Bitte melden Sie sich an, um ihr Projektmanagement anzuzeigen!');
            }



            return $block;
    }
}


