<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 01.11.16
 * Time: 15:57
 */

function gantt_chart_menu() {
    $items['gantt_chart'] = array(
        'title' => 'Gantt-Chart',
        'page callback' => 'create_gantt_chart',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function create_gantt_chart() {
    $string = "";

    $string .= '<!DOCTYPE html>
<html>
<head>
<title>Gantt Chart Example 3</title>
</head>
<body>
	<button type="button" onclick="addTask()">Add Task</button>
	<button type="button" onclick="removeTask()">Remove Task</button>
	<button type="button" onclick="changeTimeDomain(\'1hr\')">1 HR</button>
	<button type="button" onclick="changeTimeDomain(\'3hr\')">3 HR</button>
	<button type="button" onclick="changeTimeDomain(\'6hr\')">6 HR</button>
        <button type="button" onclick="changeTimeDomain(\'1day\')">1 DAY</button>
        <button type="button" onclick="changeTimeDomain(\'1week\')">1 WEEK</button>
</body>
</html>
        <script type="text/javascript" src="http://d3js.org/d3.v3.min.js"></script>
	<script type="text/javascript" src="http://static.mentful.com/gantt-chart-d3v2.js"></script>
	<script type="text/javascript" src="example3.js"></script>';
    return $string;
}