<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 03.03.17
 * Time: 10:15
 */

/**
 * Implements hook_menu().
 */
function mymodule_menu() {
    $items = array();

    $items['mymodule/page'] = array(
        'page callback' => 'test_module_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['mymodule/%ctools_js/%'] = array(
        'page callback' => 'test_module_callback',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * Helper function to make a link.
 */
function _test_module_make_link($link_text = '') {
    // Set a default value if no text in supplied.
    if (empty($link_text)) {
        $link_text = 'Magical Modal';
    }

    return '<div id="magical-modal-link">' . l($link_text, 'mymodule/nojs/x', array('attributes' => array('class' => 'ctools-use-modal'))) . '</div>';
}

/**
 * An example page.
 */
function test_module_page() {
    // Load the modal library and add the modal javascript.
    ctools_include('modal');
    ctools_modal_add_js();
    return _test_module_make_link('Magical modal');
}

/**
 * Ajax menu callback.
 */
function test_module_callback($ajax) {
    if ($ajax) {
        ctools_include('ajax');
        ctools_include('modal');

        $form_state = array(
            'ajax' => TRUE,
            'title' => t('MyModule Modal Form'),
        );

        // Use ctools to generate ajax instructions for the browser to create
        // a form in a modal popup.
        $output = ctools_modal_form_wrapper('test_module_form', $form_state);

        // If the form has been submitted, there may be additional instructions
        // such as dismissing the modal popup.
        if (!empty($form_state['ajax_commands'])) {
            $output = $form_state['ajax_commands'];
        }

        // Return the ajax instructions to the browser via ajax_render().
        print ajax_render($output);
        drupal_exit();
    }
    else {
        return drupal_get_form('test_module_form');
    }
}

/**
 * Drupal form to be put in a modal.
 */
function test_module_form($form, $form_state) {
    $form = array();

    $test = "<h1>HEHE Hat geklappt</h1>";


    $form['form_item'] = array(
        '#type' => 'markup',
        '#title' => t('My Form Item'),
        '#prefix' => $test,
    );

    return $form;
}
